FROM tensorflow/tensorflow:latest

WORKDIR /db

RUN pip install --no-cache-dir --no-deps tensorflow-text tensorflow-hub sentencepiece tf_keras && \
    pip install --no-cache-dir --ignore-installed blinker flask chromadb==0.6.3