FROM tensorflow/tensorflow:latest

WORKDIR /db

RUN pip install --upgrade pip && \
    pip3 install --no-deps tensorflow-text tensorflow-hub sentencepiece && \
    pip3 install --ignore-installed blinker tf_keras chromadb==0.6.3 flask